import "@/styles/globals.css";
import "@rainbow-me/rainbowkit/styles.css";
import { getDefaultWallets, RainbowKitProvider } from "@rainbow-me/rainbowkit";
import { configureChains, createClient, WagmiConfig } from "wagmi";
import { goerli, hardhat, polygonMumbai, sepolia } from "wagmi/chains";
import { alchemyProvider } from "wagmi/providers/alchemy";
import { jsonRpcProvider } from "@wagmi/core/providers/jsonRpc";
import { infuraProvider } from "wagmi/providers/infura";
import { publicProvider } from "wagmi/providers/public"; //isme kon sa provider aata h and kha se aata h,link kya h hmne to n diya ise khi,,hm to pana alg se isse niche de hi rhe h fir iski jrurt kyu h..hmara n mile to ye kha se kese connect krega fir hmari kya jrurt ye kr hi lega to pta lgao..
import Head from "next/head";
import Header from "@/components/Header";
import { HomeProvider } from "@/contexts/stakingContext";
import { ContractDataProvider } from "@/contexts/contractDataContext";
import { ToastContainer } from "react-toastify";
import React from "react";

//Ans:
//Only having publicProvider in your providers will make the chain use the public RPC URL which could lead to rate-limiting. It is recommended to also include another provider in your list (such as: alchemyProvider, infuraProvider or jsonRpcProvider).

export default function App({ Component, pageProps }) {
  const { chains, provider } = configureChains(
    [goerli, sepolia, polygonMumbai, hardhat],
    [
      publicProvider(),
      alchemyProvider({ apiKey: process.env.NEXT_PUBLIC_ALCHEMY_ID_GOERLI }),
      alchemyProvider({ apiKey: process.env.NEXT_PUBLIC_ALCHEMY_ID_SEPOLIA }),
      alchemyProvider({ apiKey: process.env.NEXT_PUBLIC_ALCHEMY_ID_MUMBAI }),
      jsonRpcProvider({
        rpc: (chain) => ({
          http: `http://127.0.0.1:8545/`,
        }),
      }),
    ]
  );
  // console.log(provider);
  const { connectors } = getDefaultWallets({
    appName: "My RainbowKit App",
    chains,
  });
  const wagmiClient = createClient({
    autoConnect: true,
    connectors,
    provider,
  });
  return (
    <WagmiConfig client={wagmiClient}>
      <RainbowKitProvider chains={chains}>
        <HomeProvider>
          <ContractDataProvider>
            <Head>
              <title>Staking DApp</title>
              <meta name="description" content="Generated by create next app" />
              <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
              />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <ToastContainer />
            {/**ye ek trike se header ki tarh h jo sb page pr aa skta h jb bhi toast.<method> khi code m call honge ye hi component ren der hoga page pr jha bhi ho */}
            <Component {...pageProps} />
          </ContractDataProvider>
        </HomeProvider>
      </RainbowKitProvider>
    </WagmiConfig>
  );
}
